/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Discovered hardware key backend */
export interface HardwareKeyInfo {
  /** "yubikey-piv" or "secure-enclave" */
  backend: string
  /** Human-readable description */
  description: string
  /** Supported algorithms: "ES256", "RS256", etc. */
  algorithms: Array<string>
  /** For YubiKey: serial number. For Secure Enclave: "local" */
  deviceId: string
}
/** Result of key generation */
export interface GeneratedKey {
  /** Backend that holds the key */
  backend: string
  /** Key identifier (slot for PIV, tag for Secure Enclave) */
  keyId: string
  /** Algorithm used */
  algorithm: string
  /** Public key as JWK JSON string */
  publicJwk: string
}
/** Result of a signing operation */
export interface SignatureResult {
  /** Raw signature bytes (r||s for ECDSA, raw for RSA) */
  signature: Buffer
  /** Algorithm used */
  algorithm: string
}
/** Discover available hardware key backends */
export declare function discover(): Array<HardwareKeyInfo>
/**
 * Generate a key on the specified backend.
 *
 * # Parameters (Secure Enclave only)
 * - `label`              – Key label stored as `kSecAttrApplicationLabel`. Required for
 *                          Secure Enclave; ignored for YubiKey (slot is fixed to 9e).
 * - `permanent`          – Persist to keychain (`kSecAttrIsPermanent`). Requires the
 *                          binary to be codesigned with `keychain-access-groups`.
 *                          Ignored for YubiKey.
 * - `require_biometric`  – When `true`, Touch ID / Face ID is prompted on every signing
 *                          operation (`kSecAccessControlBiometryAny`). When `false`,
 *                          the key is usable programmatically with no user interaction.
 *                          Ignored for YubiKey.
 * - `replace_if_exists`  – When `true` and `label` already exists, the old key is
 *                          deleted before creating a new one. When `false` and the key
 *                          already exists in the keychain it is loaded into the
 *                          in-process cache and returned as-is. Ignored for YubiKey.
 */
export declare function generateKey(backend: string, algorithm: string, label?: string | undefined | null, permanent?: boolean | undefined | null, requireBiometric?: boolean | undefined | null, replaceIfExists?: boolean | undefined | null): GeneratedKey
/**
 * Sign a hash with a hardware key.
 * For JWT: pass the SHA-256 hash of the `header.payload` string.
 */
export declare function signHash(backend: string, keyId: string, hash: Buffer): Promise<SignatureResult>
/**
 * List existing keys on a backend.
 *
 * - `prefix` – Optional label prefix filter (Secure Enclave only; ignored for YubiKey).
 */
export declare function listKeys(backend: string, prefix?: string | undefined | null): Array<GeneratedKey>
/**
 * Delete a key by label.
 *
 * For Secure Enclave: removes from the in-process cache and keychain (if permanent).
 * For YubiKey: no-op — PIV slots cannot be deleted, only overwritten via `generate_key`.
 */
export declare function deleteKey(backend: string, label: string): void
